services:
    # First we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: AppBundle\Utils\Slugger

    markdown:
        class: AppBundle\Utils\Markdown

    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ["@markdown"]
        tags:
            - { name: twig.extension }

    app.twig.locale_extension:
        public:    false
        class:     AppBundle\Twig\LocaleExtension
        arguments: ["%app_locales%"]
        tags:
            - { name: twig.extension }

    app.twig.source_code_extension:
        public:    false
        class:     AppBundle\Twig\SourceCodeExtension
        arguments: ["@twig.loader", "%kernel.root_dir%"]
        tags:
            - { name: twig.extension }

    app.twig.extension_intl:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.controller_listener:
        class:     AppBundle\EventListener\ControllerListener
        arguments: ["@app.twig.source_code_extension"]
        tags:
            - { name: 'kernel.event_listener', event: kernel.controller, method: registerCurrentController }

    user_provider:
        class: AppBundle\Security\User\UserProvider
        arguments:
            - @user_repository

    post_repository:
        class:     AppBundle\Repository\PostRepository
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: [AppBundle\Entity\Post]

    comment_repository:
        class:     AppBundle\Repository\CommentRepository
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: [AppBundle\Entity\Comment]

    user_repository:
        class:     AppBundle\Repository\UserRepository
        factory:   ["@doctrine.orm.entity_manager", getRepository]
        arguments: [AppBundle\Entity\User]
